import java.util.Scanner;

abstract class ReportGenerator {

    public final void generateReport() {
        log("Starting report generation process...");
        createHeader();
        formatData();
        if (customerWantsSave()) {
            saveReport();
            log("Report saved successfully.");
        }
        if (customerWantsEmail()) {
            sendByEmail();
            log("Report sent via email.");
        }
        createFooter();
        log("Report generation finished.\n");
    }

    protected abstract void createHeader();
    protected abstract void formatData();
    protected abstract void saveReport();

    protected void createFooter() {
        System.out.println("Default Footer: Generated by SmartReport System.");
    }

    protected boolean customerWantsSave() {
        return true;
    }

    protected boolean customerWantsEmail() {
        return false;
    }

    protected void sendByEmail() {
        System.out.println("Sending report to default email address...");
    }

    protected void log(String message) {
        System.out.println("[LOG]: " + message);
    }

    protected boolean getUserConfirmation(String message) {
        Scanner scanner = new Scanner(System.in);
        while (true) {
            System.out.print(message + " (y/n): ");
            String answer = scanner.nextLine().trim().toLowerCase();
            if (answer.equals("y")) return true;
            if (answer.equals("n")) return false;
            System.out.println("Error: Invalid input. Please enter 'y' or 'n'.");
        }
    }
}

class PdfReport extends ReportGenerator {
    @Override
    protected void createHeader() {
        System.out.println("PDF: Creating stylish vector header.");
    }

    @Override
    protected void formatData() {
        System.out.println("PDF: Formatting data into fixed-layout tables.");
    }

    @Override
    protected void saveReport() {
        System.out.println("PDF: Saving file as .pdf");
    }
}

class ExcelReport extends ReportGenerator {
    @Override
    protected void createHeader() {
        System.out.println("Excel: Creating header with frozen panes.");
    }

    @Override
    protected void formatData() {
        System.out.println("Excel: Converting data into cells and formulas.");
    }

    @Override
    protected void saveReport() {
        System.out.println("Excel: Saving file as .xlsx");
    }

    @Override
    protected boolean customerWantsSave() {
        return getUserConfirmation("Do you want to save the Excel file?");
    }
}

class HtmlReport extends ReportGenerator {
    @Override
    protected void createHeader() {
        System.out.println("HTML: Adding <header> tag with CSS styles.");
    }

    @Override
    protected void formatData() {
        System.out.println("HTML: Generating <table> and <div> elements.");
    }

    @Override
    protected void saveReport() {
        System.out.println("HTML: Saving as index.html");
    }

    @Override
    protected void createFooter() {
        System.out.println("HTML Footer: <footer>Powered by WebService</footer>");
    }
}

class CsvReport extends ReportGenerator {
    private boolean sendEmail;

    public CsvReport(boolean sendEmail) {
        this.sendEmail = sendEmail;
    }

    @Override
    protected void createHeader() {
        System.out.println("CSV: Adding column names separated by commas.");
    }

    @Override
    protected void formatData() {
        System.out.println("CSV: Plain text data formatting.");
    }

    @Override
    protected void saveReport() {
        System.out.println("CSV: Saving file as .csv");
    }

    @Override
    protected boolean customerWantsSave() {
        return !sendEmail;
    }

    @Override
    protected boolean customerWantsEmail() {
        return sendEmail;
    }

    @Override
    protected void sendByEmail() {
        System.out.println("CSV: Attaching .csv file to the email and sending...");
    }
}

public class Main {
    public static void main(String[] args) {
        System.out.println("--- PDF Generation ---");
        ReportGenerator pdf = new PdfReport();
        pdf.generateReport();

        System.out.println("--- Excel Generation ---");
        ReportGenerator excel = new ExcelReport();
        excel.generateReport();

        System.out.println("--- HTML Generation ---");
        ReportGenerator html = new HtmlReport();
        html.generateReport();

        System.out.println("--- CSV Generation (Email Mode) ---");
        ReportGenerator csv = new CsvReport(true);
        csv.generateReport();
    }
}
